In [1]:
import mysql.connector
import pandas as pd

# Connect to MySQL
conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="Kratos@123",
    database="gow_armors"
)

# Create cursor
cursor = conn.cursor()

# Execute SQL query
cursor.execute("SELECT * FROM armors")

# Fetch all rows
rows = cursor.fetchall()

# Get column names
columns = [column[0] for column in cursor.description]

# Create Pandas DataFrame
df = pd.DataFrame(rows, columns=columns)

# Display first 5 rows
print(df.head())

# Display column names
print(df.columns)

   ID                    Title Category  Strength  Defence  Runic  Vitality  \
0   1           Cuiras of Ares    Chest        52       42      0        31
1   2         Gauntlet of Ares    Wrist       113        0      0        38
2   3          Warbelt of Ares    Waist       113        0      0        38
3   4  Cloak of the Black Bear    Chest       120      120      0         0
4   5  Wraps of the Black Bear    Wrist       125       25      0         0

   Cooldown  Luck                                              Skill
0         0    31  rage hits have a chance to deploy healthstone ...
1         0    38  when rage meter is full using it willincrease ...
2         0    38  when rage meter is full using it willincrease ...
3        40     0  Kratos first Melee Attack immediately after ev...
4        25     0  Increases immunity duration while evading and ...
Index(['ID', 'Title', 'Category', 'Strength', 'Defence', 'Runic', 'Vitality',
       'Cooldown', 'Luck', 'Skill'],
      dtype='str')

In [2]:
print(df.head())  # show first few coloums and raws

   ID                    Title Category  Strength  Defence  Runic  Vitality  \
0   1           Cuiras of Ares    Chest        52       42      0        31
1   2         Gauntlet of Ares    Wrist       113        0      0        38
2   3          Warbelt of Ares    Waist       113        0      0        38
3   4  Cloak of the Black Bear    Chest       120      120      0         0
4   5  Wraps of the Black Bear    Wrist       125       25      0         0

   Cooldown  Luck                                              Skill
0         0    31  rage hits have a chance to deploy healthstone ...
1         0    38  when rage meter is full using it willincrease ...
2         0    38  when rage meter is full using it willincrease ...
3        40     0  Kratos first Melee Attack immediately after ev...
4        25     0  Increases immunity duration while evading and ...

In [3]:
print(df.tail())  # show last  few coloums and raws

    ID              Title Category  Strength  Defence  Runic  Vitality  \
82  83    Pride of Sparta    Wrist       169        0      0        63
83  84     Mark of Sparta    Waist        69      100      0        63
84  85    Cuirass of Zeus    Chest       100      100     80         0
85  86  Gauntlets of Zeus    Wrist       125        0     50         0
86  87   War Belt of Zeus    Waist         0      120     50         0

    Cooldown  Luck                                              Skill
82         0     0                                               None
83         0     0                                               None
84         0     0  Increases Kratos' Melee and Runic Damage by 40...
85         0     0  Increases Kratos' Melee and Runic Damage by 20...
86         0     0  Increases Kratos' Melee and Runic Damage by 20...

In [4]:
print("shape", df.shape)   #total number of rowas and coloums

shape (87, 10)

In [5]:
print("info : ", df.info)   # print all rows and coloums scribe count, mean, std, min, %, max etc

info :  <bound method DataFrame.info of     ID                    Title Category  Strength  Defence  Runic  Vitality  \
0    1           Cuiras of Ares    Chest        52       42      0        31
1    2         Gauntlet of Ares    Wrist       113        0      0        38
2    3          Warbelt of Ares    Waist       113        0      0        38
3    4  Cloak of the Black Bear    Chest       120      120      0         0
4    5  Wraps of the Black Bear    Wrist       125       25      0         0
..  ..                      ...      ...       ...      ...    ...       ...
82  83          Pride of Sparta    Wrist       169        0      0        63
83  84           Mark of Sparta    Waist        69      100      0        63
84  85          Cuirass of Zeus    Chest       100      100     80         0
85  86        Gauntlets of Zeus    Wrist       125        0     50         0
86  87         War Belt of Zeus    Waist         0      120     50         0

    Cooldown  Luck                                              Skill
0          0    31  rage hits have a chance to deploy healthstone ...
1          0    38  when rage meter is full using it willincrease ...
2          0    38  when rage meter is full using it willincrease ...
3         40     0  Kratos first Melee Attack immediately after ev...
4         25     0  Increases immunity duration while evading and ...
..       ...   ...                                                ...
82         0     0                                               None
83         0     0                                               None
84         0     0  Increases Kratos' Melee and Runic Damage by 40...
85         0     0  Increases Kratos' Melee and Runic Damage by 20...
86         0     0  Increases Kratos' Melee and Runic Damage by 20...

[87 rows x 10 columns]>

data Filtering

In [6]:
print(df[df["Category"] == "Chest"]) # fiter all chest armors in table/dtaframe
print(df[df["Defence"] > 150])
print("Defence Chest : ", df[df["Defence"]  == "Chest"])
print("Defence unique : ", df["Category"].unique()) #filter all armor type by "chest wrist and "waist"

    ID                            Title Category  Strength  Defence  Runic  \
0    1                   Cuiras of Ares    Chest        52       42      0
3    4          Cloak of the Black Bear    Chest       120      120      0
6    7       Shoulder Guard of Survival    Chest       100      100     53
9   10           Fortified Husk Cuirass    Chest       100      180      0
12  13        Vidar's Pauldron of Might    Chest       170      100      0
15  16           Risen Snow Breastplate    Chest       125        0      0
18  19                Darkdale Plackart    Chest       100      100     50
21  22     Niðavellir's Finest Plackart    Chest        80      140      0
24  25       Spaulders of Enlightenment    Chest        80      100    110
27  28           Cuirass of Raven Tears    Chest        70      160      0
30  31      Shoulder Straps of Radiance    Chest       120       70      0
33  34       Sól's Spaulders of Courage    Chest        80      100      0
36  37        Spiritual Shoulder Straps    Chest       100       80      0
39  40       Sól's Spaulders of Courage    Chest        80      100      0
42  43             Lúnda's Lost Cuirass    Chest       100       80     40
45  46     Breastplate of Guiding Light    Chest       100       80      0
48  49          Giptumaðr's Breastplate    Chest        80      100     30
51  52        Máni's Pauldron of Wisdom    Chest        80      100     40
54  55                Berserker Cuirass    Chest       100       40     60
57  58              Steinbjörn Plackart    Chest       280        0      0
60  61         Plackart of Fallen Stars    Chest        80      100     90
63  64        Dragon Scaled Breastplate    Chest       140      140      0
66  67  Shoulder Guard of Undying Pyres    Chest       100       80     80
69  70                Hunter's Pauldron    Chest       100       80     80
72  73      Fate Breaker Shoulder Guard    Chest       100       80      0
75  76         Surtr's Scorched Cuirass    Chest       120      100      0
78  79                 Sorrow of Sparta    Chest         0        0      0
81  82                  Glory of Sparta    Chest       190       80      0
84  85                  Cuirass of Zeus    Chest       100      100     80

    Vitality  Cooldown  Luck  \
0         31         0    31
3          0        40     0
6         53        53    53
9          0         0     0
12         0         0     0
15         0        31    31
18        50         0     0
21        80         0     0
24         0         0     0
27         0         0    70
30        60         0    60
33       100       100     0
36        60       100     0
39       100       100     0
42         0         0    80
45         0         0   100
48         0         0    90
51         0        80     0
54        60        60    60
57         0         0     0
60        30         0     0
63         0         0     0
66         0        40     0
69         0        40     0
72        90        30     0
75        70         0     0
78         0         0     0
81       100         0     0
84         0         0     0

                                                Skill
0   rage hits have a chance to deploy healthstone ...
3   Kratos first Melee Attack immediately after ev...
6                                                None
9   Blocks and Parries have a Moderate LUCK chance...
12  Combo Finishers have a High LUCK chance to inc...
15  Launching an enemy has a High LUCK chance to i...
18  Killing an enemy while in Spartan Rage restore...
21      Stun Grabbing an enemy grants a Health Burst.
24  Frost Awaken and Flame Whiplash hits have a Mo...
27  Hitting enemies has a Low LUCK chance to grant...
30  Moderate LUCK chance to grant a Blessing of RU...
33  Kratos' Melee damage increases based on his Ra...
36  Runic or Relic Attack hits stack a buff increa...
39  Kratos' Melee damage increases based on his Ra...
42  Bare-Handed attacks, Parrying, and Blocking ha...
45  Moderate LUCK chance on any hit to increase th...
48  Moderate LUCK chance when using a Runic Attack...
51  Increases the damage caused by the Extinguish ...
54  Using a Relic massively increases the damage o...
57  After significant damage is taken, Kratos' att...
60  Greatly reduces damage taken when using a Runi...
63  Blocks and Parries grant a buff of increasing ...
66  When the Permafrost, Immolation, or Maelstrom ...
69  When the Permafrost, Immolation, or Maelstrom ...
72  After returning from Rage, get a brief buff to...
75  Kratos' attacks that hit enemies during their ...
78                                               None
81                                               None
84  Increases Kratos' Melee and Runic Damage by 40...
    ID                   Title Category  Strength  Defence  Runic  Vitality  \
9   10  Fortified Husk Cuirass    Chest       100      180      0         0
11  12   Fortified Husk Girdle    Waist         0      175      0         0
27  28  Cuirass of Raven Tears    Chest        70      160      0         0
59  60  Steinbjörn Waist Guard    Waist         0      175      0         0

    Cooldown  Luck                                              Skill
9          0     0  Blocks and Parries have a Moderate LUCK chance...
11         0     0  While Blocking, take less damage from unblocka...
27         0    70  Hitting enemies has a Low LUCK chance to grant...
59         0     0  Moderate LUCK chance to stagger and inflict St...
Defence Chest :  Empty DataFrame
Columns: [ID, Title, Category, Strength, Defence, Runic, Vitality, Cooldown, Luck, Skill]
Index: []
Defence unique :  <StringArray>
['Chest', 'Wrist', 'Waist']
Length: 3, dtype: str

2. Data sorting

In [7]:
df.sort_values(by='Defence', ascending = False)   #by="defence" → sort defense according to coloumn, ascending=False → highest → lowest

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
9,10,Fortified Husk Cuirass,Chest,100,180,0,0,0,0,Blocks and Parries have a Moderate LUCK chance...
11,12,Fortified Husk Girdle,Waist,0,175,0,0,0,0,"While Blocking, take less damage from unblocka..."
59,60,Steinbjörn Waist Guard,Waist,0,175,0,0,0,0,Moderate LUCK chance to stagger and inflict St...
27,28,Cuirass of Raven Tears,Chest,70,160,0,0,0,70,Hitting enemies has a Low LUCK chance to grant...
63,64,Dragon Scaled Breastplate,Chest,140,140,0,0,0,0,Blocks and Parries grant a buff of increasing ...
...,...,...,...,...,...,...,...,...,...,...
76,77,Surtr's Scorched Arm,Wrist,138,0,0,44,0,0,Kratos takes reduced damage and has increased ...
82,83,Pride of Sparta,Wrist,169,0,0,63,0,0,None
80,81,Woe of Sparta,Waist,0,0,0,0,0,0,None
79,80,Scars of Sparta,Wrist,0,0,0,0,0,0,None
85,86,Gauntlets of Zeus,Wrist,125,0,50,0,0,0,Increases Kratos' Melee and Runic Damage by 20...

In [8]:
df.sort_values(by='Defence', ascending = False)

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
9,10,Fortified Husk Cuirass,Chest,100,180,0,0,0,0,Blocks and Parries have a Moderate LUCK chance...
11,12,Fortified Husk Girdle,Waist,0,175,0,0,0,0,"While Blocking, take less damage from unblocka..."
59,60,Steinbjörn Waist Guard,Waist,0,175,0,0,0,0,Moderate LUCK chance to stagger and inflict St...
27,28,Cuirass of Raven Tears,Chest,70,160,0,0,0,70,Hitting enemies has a Low LUCK chance to grant...
63,64,Dragon Scaled Breastplate,Chest,140,140,0,0,0,0,Blocks and Parries grant a buff of increasing ...
...,...,...,...,...,...,...,...,...,...,...
76,77,Surtr's Scorched Arm,Wrist,138,0,0,44,0,0,Kratos takes reduced damage and has increased ...
82,83,Pride of Sparta,Wrist,169,0,0,63,0,0,None
80,81,Woe of Sparta,Waist,0,0,0,0,0,0,None
79,80,Scars of Sparta,Wrist,0,0,0,0,0,0,None
85,86,Gauntlets of Zeus,Wrist,125,0,50,0,0,0,Increases Kratos' Melee and Runic Damage by 20...

In [9]:
df.sort_values(by='Defence', ascending = True)   # lowest to highest

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
1,2,Gauntlet of Ares,Wrist,113,0,0,38,0,38,when rage meter is full using it willincrease ...
2,3,Warbelt of Ares,Waist,113,0,0,38,0,38,when rage meter is full using it willincrease ...
13,14,Vidar's Bracers of Might,Wrist,169,0,0,0,0,0,Combo Finishers do increased damage. (10% alon...
15,16,Risen Snow Breastplate,Chest,125,0,0,0,31,31,Launching an enemy has a High LUCK chance to i...
25,26,Bracers of Enlightenment,Wrist,110,0,63,0,0,0,Runic Attacks do increased damage against Stat...
...,...,...,...,...,...,...,...,...,...,...
21,22,Niðavellir's Finest Plackart,Chest,80,140,0,80,0,0,Stun Grabbing an enemy grants a Health Burst.
27,28,Cuirass of Raven Tears,Chest,70,160,0,0,0,70,Hitting enemies has a Low LUCK chance to grant...
11,12,Fortified Husk Girdle,Waist,0,175,0,0,0,0,"While Blocking, take less damage from unblocka..."
59,60,Steinbjörn Waist Guard,Waist,0,175,0,0,0,0,Moderate LUCK chance to stagger and inflict St...
9,10,Fortified Husk Cuirass,Chest,100,180,0,0,0,0,Blocks and Parries have a Moderate LUCK chance...

In [10]:

df.sort_values(by="Strength", ascending=False).head(5)

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
57,58,Steinbjörn Plackart,Chest,280,0,0,0,0,0,"After significant damage is taken, Kratos' att..."
81,82,Glory of Sparta,Chest,190,80,0,100,0,0,None
12,13,Vidar's Pauldron of Might,Chest,170,100,0,0,0,0,Combo Finishers have a High LUCK chance to inc...
13,14,Vidar's Bracers of Might,Wrist,169,0,0,0,0,0,Combo Finishers do increased damage. (10% alon...
82,83,Pride of Sparta,Wrist,169,0,0,63,0,0,None

In [11]:
df.sort_values(by="Runic", ascending=False).head(5)

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
24,25,Spaulders of Enlightenment,Chest,80,100,110,0,0,0,Frost Awaken and Flame Whiplash hits have a Mo...
60,61,Plackart of Fallen Stars,Chest,80,100,90,30,0,0,Greatly reduces damage taken when using a Runi...
66,67,Shoulder Guard of Undying Pyres,Chest,100,80,80,0,40,0,"When the Permafrost, Immolation, or Maelstrom ..."
69,70,Hunter's Pauldron,Chest,100,80,80,0,40,0,"When the Permafrost, Immolation, or Maelstrom ..."
84,85,Cuirass of Zeus,Chest,100,100,80,0,0,0,Increases Kratos' Melee and Runic Damage by 40...

In [12]:

df.sort_values(by="Runic", ascending=True).tail(5)

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
66,67,Shoulder Guard of Undying Pyres,Chest,100,80,80,0,40,0,"When the Permafrost, Immolation, or Maelstrom ..."
69,70,Hunter's Pauldron,Chest,100,80,80,0,40,0,"When the Permafrost, Immolation, or Maelstrom ..."
84,85,Cuirass of Zeus,Chest,100,100,80,0,0,0,Increases Kratos' Melee and Runic Damage by 40...
60,61,Plackart of Fallen Stars,Chest,80,100,90,30,0,0,Greatly reduces damage taken when using a Runi...
24,25,Spaulders of Enlightenment,Chest,80,100,110,0,0,0,Frost Awaken and Flame Whiplash hits have a Mo...

3.Loc(label based ndexing)

In [13]:
df.loc[:, ["Defence", "Category", "Luck"]] #[: this defines the all rows

    Defence Category  Luck
0        42    Chest    31
1         0    Wrist    38
2         0    Waist    38
3       120    Chest     0
4        25    Wrist     0
..      ...      ...   ...
82        0    Wrist     0
83      100    Waist     0
84      100    Chest     0
85        0    Wrist     0
86      120    Waist     0

[87 rows x 3 columns]

In [14]:
df.loc[0:5, ["Defence", "Category", "Luck"]]  # [0:5 this defines from rows 0 to 5

   Defence Category  Luck
0       42    Chest    31
1        0    Wrist    38
2        0    Waist    38
3      120    Chest     0
4       25    Wrist     0
5      125    Waist     0

In [15]:
df.loc[df["Defence"] > 150, ["Defence", "Category", "Strength"]] # show name and strength of deDefencefense > 150

    Defence Category  Strength
9       180    Chest       100
11      175    Waist         0
27      160    Chest        70
59      175    Waist         0

In [16]:
df.iloc[:,0]

0      1
1      2
2      3
3      4
4      5
      ..
82    83
83    84
84    85
85    86
86    87
Name: ID, Length: 87, dtype: int64

df.loc[CONDITION, COLUMNS]

1. loc  → naam/label   
2. iloc → number/position iloc shows index numbers

In [17]:
df.iloc[1]  # it shows specific row according to their address (start from 0 to n.) o included or we can say that start but n term is not included

ID                                                          2
Title                                        Gauntlet of Ares
Category                                                Wrist
Strength                                                  113
Defence                                                     0
Runic                                                       0
Vitality                                                   38
Cooldown                                                    0
Luck                                                       38
Skill       when rage meter is full using it willincrease ...
Name: 1, dtype: object

4.Value Counts

In Pandas, value_counts() is a fundamental data exploration tool used to calculate the frequency distribution of unique items within a dataset. It essentially functions as a built-in histogram or tally sheet, summarizing how many times each distinct value appears.

syntax--- df["armor_type"].value_counts()

In [18]:
df["Defence"].max()

np.int64(180)

In [19]:
df["Strength"].max()

np.int64(280)

In [20]:
df["Defence"].mean() # average defence

np.float64(72.08045977011494)

In [21]:
df.sort_values("Defence", ascending = False).head(9)

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
9,10,Fortified Husk Cuirass,Chest,100,180,0,0,0,0,Blocks and Parries have a Moderate LUCK chance...
11,12,Fortified Husk Girdle,Waist,0,175,0,0,0,0,"While Blocking, take less damage from unblocka..."
59,60,Steinbjörn Waist Guard,Waist,0,175,0,0,0,0,Moderate LUCK chance to stagger and inflict St...
27,28,Cuirass of Raven Tears,Chest,70,160,0,0,0,70,Hitting enemies has a Low LUCK chance to grant...
63,64,Dragon Scaled Breastplate,Chest,140,140,0,0,0,0,Blocks and Parries grant a buff of increasing ...
21,22,Niðavellir's Finest Plackart,Chest,80,140,0,80,0,0,Stun Grabbing an enemy grants a Health Burst.
23,24,Niðavellir's Finest Waist Guard,Waist,0,138,0,0,50,0,Reduces how quickly enemy Stun bars drain. (50...
65,66,Dragon Scaled Girdle,Waist,38,137,0,0,0,0,Getting hit while using a Runic Attack or Reli...
20,21,Darkdale Waist Guard,Waist,0,125,0,0,31,31,Increases the rate at which rage is gained whe...

In [22]:
df["Category"].value_counts() # check all types of armors count

Category
Chest    29
Wrist    29
Waist    29
Name: count, dtype: int64

In [23]:
df["Category"].value_counts(normalize= True) * 100  # it tell the persentage of all armor types

Category
Chest    33.333333
Wrist    33.333333
Waist    33.333333
Name: proportion, dtype: float64

In [24]:
df[df["Strength"] == df["Strength"].max()]

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
57,58,Steinbjörn Plackart,Chest,280,0,0,0,0,0,"After significant damage is taken, Kratos' att..."

1. df["strength"].max() → highest strength search
2. df["strength"] == ... → find where highest strength is 
3. df[...] → show the full row

In [25]:
df[df["Defence"] == df["Defence"].max()]

,ID,Title,Category,Strength,Defence,Runic,Vitality,Cooldown,Luck,Skill
9,10,Fortified Husk Cuirass,Chest,100,180,0,0,0,0,Blocks and Parries have a Moderate LUCK chance...

In [26]:
df.isnull().sum()

ID          0
Title       0
Category    0
Strength    0
Defence     0
Runic       0
Vitality    0
Cooldown    0
Luck        0
Skill       0
dtype: int64

In [27]:
df.isnull().any()

ID          False
Title       False
Category    False
Strength    False
Defence     False
Runic       False
Vitality    False
Cooldown    False
Luck        False
Skill       False
dtype: bool

In [28]:
df.describe() # it tells the oversll statics of numeric column

,ID,Strength,Defence,Runic,Vitality,Cooldown,Luck
count,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000
mean,44.000000,77.540230,72.080460,16.609195,17.678161,17.172414,14.747126
std,25.258662,58.378836,53.333575,26.843802,28.663036,27.074921,25.192846
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,22.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,44.000000,100.000000,94.000000,0.000000,0.000000,0.000000,0.000000
75%,65.500000,113.000000,113.000000,31.000000,31.000000,31.000000,31.000000
max,87.000000,280.000000,180.000000,110.000000,100.000000,100.000000,100.000000

In [29]:
df.groupby("Category")["Strength"].mean() # Chest, Wrist, Waist — it tells the average mean of all

Category
Chest    105.068966
Waist     13.482759
Wrist    114.068966
Name: Strength, dtype: float64

In [30]:
df.groupby("Category")["Defence"].mean()

Category
Chest     88.000000
Waist    110.034483
Wrist     18.206897
Name: Defence, dtype: float64

In [31]:
df.groupby("Category")[["Defence", "Runic", "Luck"]].mean() # to find more than 1 type use dobule square [[]]

             Defence      Runic       Luck
Category
Chest      88.000000  24.586207  19.827586
Waist     110.034483  10.793103  13.379310
Wrist      18.206897  14.448276  11.034483

In [32]:
df.groupby("Category")[["Defence", "Runic", "Luck"]].max()

          Defence  Runic  Luck
Category
Chest         180    110   100
Waist         175     63    63
Wrist         125     63    63

In [33]:
# Create cursor
cursor = conn.cursor()

# Execute SQL query
cursor.execute("SELECT * FROM Relics")

# Fetch all rows
rows = cursor.fetchall()

# Get column names
columns = [column[0] for column in cursor.description]

# Create Pandas DataFrame
df = pd.DataFrame(rows, columns=columns)

# Display first 5 rows
print(df.head())

# Display column names
print(df.columns)

   ID              Title                                             Effect  \
0   1  Talisman of Meign  Grants a bonus to Melee damage for a short dur...
1   2       Hilt of Gram  Grants a burst of Rage and applies Stun to nea...
2   3   Glaive of Dødher  Throw a Bifröst chakram that swerves into enem...
3   4      Hilt of Hofuð  \tDistort space and time by creating a Realm S...
4   5     Hilt of Hrotti  Applies a mark to nearby enemies. Attacking a ...

      Cooldown                                           Overview
0  120 Seconds  A talisman so precious to the previous owner, ...
1  120 Seconds  Once referred to as the Dragon's Bane, Gram is...
2  120 Seconds  The glaive thrown by the Einherjar is synonymo...
3  260 Seconds  The sword once wielded by the Watchdog of the ...
4  180 Seconds  Said to be kept in Fafnir's Storeroom. It must...
Index(['ID', 'Title', 'Effect', 'Cooldown', 'Overview'], dtype='str')

In [34]:
print(df.tail())

    ID               Title                                             Effect  \
8    9    Hilt of Skofnung  The sword unleashes its power from the souls w...
9   10  Hilt of Angrvaðall  Slash forward three waves of light that deal i...
10  11   Hilt of Dáinsleif  Slam the ground to create an explosion of Seið...
11  12      Hilt of Ridill  Unleash a wave of Shock to electrify enemies. ...
12  13     Hilt of Tyrfing  Charge the sword to sacrifice Health and deal ...

                  Cooldown                                           Overview
8              325 Seconds  The broken hilt of the King Hrólf Kraki. Once ...
9   90 Seconds (Level III)  Known as 'The Stream of Anguish', the broken s...
10             200 Seconds  Formerly the sword of King Högni. It is renown...
11             180 Seconds  It's said the sword once belonged to the Dwarf...
12  35 Seconds (Level III)  Tyrfing has a long and bloody history. Perhaps...

In [35]:
cursor.execute("SHOW TABLES")
tables = cursor.fetchall()
    
for table in tables:
    print(table[0])

armors
axe
berserkers
blades
final_recommendations
relics
rönd
shield
spear

In [36]:
cursor.execute("SELECT * FROM Blades")
rows = cursor.fetchall()

columns = [column[0] for column in cursor.description]

Blades_df = pd.DataFrame(rows, columns=columns)

Blades_df.head()

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        13 non-null     int64
 1   Title     13 non-null     str
 2   Effect    13 non-null     str
 3   Cooldown  13 non-null     str
 4   Overview  13 non-null     str
dtypes: int64(1), str(4)
memory usage: 652.0 bytes

ID          0
Title       0
Effect      0
Cooldown    0
Overview    0
dtype: int64

In [37]:
cursor.execute("SELECT * FROM Rönd")
rows = cursor.fetchall()

columns = [column[0] for column in cursor.description]

Rönd_df = pd.DataFrame(rows, columns=columns)

Rönd_df.head()

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        13 non-null     int64
 1   Title     13 non-null     str
 2   Effect    13 non-null     str
 3   Cooldown  13 non-null     str
 4   Overview  13 non-null     str
dtypes: int64(1), str(4)
memory usage: 652.0 bytes

ID          0
Title       0
Effect      0
Cooldown    0
Overview    0
dtype: int64

In [38]:
cursor.execute("SELECT * FROM Axe")
rows = cursor.fetchall()

columns = [column[0] for column in cursor.description]

Axe_df = pd.DataFrame(rows, columns=columns)

Axe_df.head()

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        13 non-null     int64
 1   Title     13 non-null     str
 2   Effect    13 non-null     str
 3   Cooldown  13 non-null     str
 4   Overview  13 non-null     str
dtypes: int64(1), str(4)
memory usage: 652.0 bytes

ID          0
Title       0
Effect      0
Cooldown    0
Overview    0
dtype: int64

In [39]:
cursor.execute("SELECT * FROM Shield")
rows = cursor.fetchall()

columns = [column[0] for column in cursor.description]

Shield_df = pd.DataFrame(rows, columns=columns)

Shield_df.head()

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        13 non-null     int64
 1   Title     13 non-null     str
 2   Effect    13 non-null     str
 3   Cooldown  13 non-null     str
 4   Overview  13 non-null     str
dtypes: int64(1), str(4)
memory usage: 652.0 bytes

ID          0
Title       0
Effect      0
Cooldown    0
Overview    0
dtype: int64

In [40]:
cursor.execute("SELECT * FROM Spear")
rows = cursor.fetchall()

columns = [column[0] for column in cursor.description]

Spear_df = pd.DataFrame(rows, columns=columns)

Spear_df.head()

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        13 non-null     int64
 1   Title     13 non-null     str
 2   Effect    13 non-null     str
 3   Cooldown  13 non-null     str
 4   Overview  13 non-null     str
dtypes: int64(1), str(4)
memory usage: 652.0 bytes

ID          0
Title       0
Effect      0
Cooldown    0
Overview    0
dtype: int64

In [41]:
cursor.execute("SELECT * FROM Relics")
rows = cursor.fetchall()

columns = [column[0] for column in cursor.description]

Relics_df = pd.DataFrame(rows, columns=columns)

Relics_df.head()

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        13 non-null     int64
 1   Title     13 non-null     str
 2   Effect    13 non-null     str
 3   Cooldown  13 non-null     str
 4   Overview  13 non-null     str
dtypes: int64(1), str(4)
memory usage: 652.0 bytes

ID          0
Title       0
Effect      0
Cooldown    0
Overview    0
dtype: int64

In [42]:
df.columns.tolist()

['ID', 'Title', 'Effect', 'Cooldown', 'Overview']

In [43]:
df.columns.tolist()

['ID', 'Title', 'Effect', 'Cooldown', 'Overview']